environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "4"
platform:
  - x64
build: off
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
branches:
  only:
  - master
clone_depth: 1
test_script:
  - node --version
  - npm --version
  - npm test
